import React from 'react'

function Price() {
  return React.createElement("div", {className:"box"},
   React.createElement("div", {className:"card"},
    React.createElement("div", {className:"card-header"},
    React.createElement("p", {className:"ptag"}, "FREE"),
    React.createElement("h2",{className:"heading"}, "$0/month")),
    React.createElement("div",{className:"card-body"},
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Single User")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "50GB Storage")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Unlimited Public Projects")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Community Access")),
    React.createElement("div",{className:"card-content-denied"},
    React.createElement("i",{className:"fa-solid fa-xmark"}),
    React.createElement("p",{className:"card-text"}, "Unlimited Private projects")),
    React.createElement("div",{className:"card-content-denied"},
    React.createElement("i",{className:"fa-solid fa-xmark"}),
    React.createElement("p",{className:"card-text"}, "Dedicated Phone Support")),
    React.createElement("div",{className:"card-content-denied"},
    React.createElement("i",{className:"fa-solid fa-xmark"}),
    React.createElement("p",{className:"card-text"}, "Free Subdomain")),
    React.createElement("div",{className:"card-content-denied"},
    React.createElement("i",{className:"fa-solid fa-xmark"}),
    React.createElement("p",{className:"card-text"}, "Monthly Status Reports")),
    React.createElement("button",{type:"button", className:"card-button"},"Button")

    )
    ),React.createElement("div", {className:"card"},
    React.createElement("div", {className:"card-header"},
    React.createElement("p", {className:"ptag"}, "PLUS"),
    React.createElement("h2",{className:"heading"}, "$9/month")),
    React.createElement("div",{className:"card-body"},
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "5 User")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "50GB Storage")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Unlimited Public Projects")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Community Access")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Unlimited Private projects")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Dedicated Phone Support")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Free Subdomain")),
    React.createElement("div",{className:"card-content-denied"},
    React.createElement("i",{className:"fa-solid fa-xmark"}),
    React.createElement("p",{className:"card-text"}, "Monthly Status Reports")),
    React.createElement("button",{type:"button", className:"card-button"},"Button")

    )
    ),React.createElement("div", {className:"card"},
    React.createElement("div", {className:"card-header"},
    React.createElement("p", {className:"ptag"}, "PRO"),
    React.createElement("h2",{className:"heading"}, "$49/month")),
    React.createElement("div",{className:"card-body"},
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Unlimited User")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "50GB Storage")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Unlimited Public Projects")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Community Access")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Unlimited Private projects")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Dedicated Phone Support")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Free Subdomain")),
    React.createElement("div",{className:"card-content-access"},
    React.createElement("i",{className:"fa-solid fa-check"}),
    React.createElement("p",{className:"card-text"}, "Monthly Status Reports")),
    React.createElement("button",{type:"button", className:"card-button"},"Button")

    )
    ));
}

export default Price